// Centralized conversation steps for the voice booking state machine
export const STEPS = {
  IDLE: "IDLE",
  ASK_NAME: "ASK_NAME",
  ASK_GUESTS: "ASK_GUESTS",
  ASK_DATE: "ASK_DATE",
  ASK_TIME: "ASK_TIME",
  ASK_CUISINE: "ASK_CUISINE",
  ASK_SPECIAL_REQUEST: "ASK_SPECIAL_REQUEST",
  FETCH_WEATHER: "FETCH_WEATHER",
  CONFIRM_DETAILS: "CONFIRM_DETAILS",
  SAVE_BOOKING: "SAVE_BOOKING",
  COMPLETE: "COMPLETE",
};
